NUM_GPUS: 2
EVAL_FREQ: 1

S2D:
  SAMPLING_RATE: 1
  TWOSTAGE_TRAINING: True
  TWOSTAGE_TRAINING_STAGE: 'WARMUP'
  TRAIN_ONLY_PARAMS: ''
  SNET_RESUME: 'pretrained/adafocus/mini_mbv2.pth.tar'
  SNET_FEATURE_DIM: 1280
  SNET_INPUT_SIZE: 144
  SNET_LR_RATIO: 1.0
  SNET_FRAME_NUM: 16
  SNET_DROPOUT: 0.5
  CVECTOR_DROPOUT: 0.5
  DETAIL_SAMPLING: True
  SPACE_SAMPLING: True
  SNET_FEATURE_LAYER: 'features' 
  SNET_LOSS_WEIGHT: 0.1
  SAMPLER_STOP_GRADIENTS: True
  CTX_STOP_GRADIENTS: False
  DNET_RESUME: 'pretrained/adafocus/mini_r50.pth.tar'
  DNET_FRAME_NUM: 16
  DNET_DROPOUT: 0.5
  LATERAL_FUSION: True
  FUSION_TYPE: 'concat-multilevel-3d'
  FUSION_LAYERS: 'layer2,layer3'
  SPACE_FOLLOW_TIME: True
  SAMPLER_OPTIM: 'sgd'
  TIME_PARAM_INIT_FACTOR: 0.05
  SPACE_PARAM_INIT_FACTOR: 0.05

ABLATION:
  SPATIAL_SAMPLE_METHOD: 'gaussian'
  TEMPORAL_SAMPLE_METHOD: 'gaussian'
  SPACE_STRIDE: 'exp'
  TIME_STRIDE: 'exp'
  USE_3D_SPACE_CONV: True
  SNET_ACTION_TYPE: 'SOMEHOT'

TRAIN:
  WEIGHT_DECAY: 1e-3
  EPOCHS: 40
  OPTIM: 'sgd'
  CLIP_GRADIENT: 20.
  LR_DECAY_TYPES: 'cos'
  FREEZE_BN: False
  WARMUP_LR: 0.5e-8

DATA:
  DATASET_REPEAT_TIMES: 1
  AUGMENTATION_SCALES: [1.0, 0.875, 0.75, 0.66]
  RAW_INPUT_SAMPLING_RATE: 2

TSM:
  NON_LOCAL: False # follows Adafocus
